runtime: python311

env: standard

entrypoint: gunicorn -w 4 -b :$PORT "src.api.main:app" --worker-class uvicorn.workers.UvicornWorker

env_variables:
  GCP_PROJECT_ID: "runagen-ai"
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: "/app/src"
  ENVIRONMENT: "cloud"
  GEMINI_API_KEY: "${GEMINI_API_KEY}"
  ADZUNA_APP_ID: "${ADZUNA_APP_ID}"
  ADZUNA_APP_KEY: "${ADZUNA_APP_KEY}"
  MONGO_URI: "${MONGO_URI}"
  MONGO_DB: "runagen_ml_warehouse"
  OLLAMA_URL: "http://34.41.182.97:11434"
  OLLAMA_MODEL: "llama3"

